### ISSUE TITLE
Running inference 

### ISSUE THREAD

**Issue by gaussiangit** [IDEA-Research/DWPose#1]
How can I run inference with dw-ll_ucoco_384.pth?
I could not find yml for that model

**Comment by github-luffy** [comment]
> The config for dw-ll_ucoco_384.pth is [this](https://github.com/IDEA-Research/DWPose/blob/main/mmpose/configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py). You can find it in README. You can refer the Test a model in README to test it. If you want to inference for your own images, you can refer [top_with_mmdet.py](https://github.com/IDEA-Research/DWPose/blob/main/mmpose/demo/topdown_demo_with_mmdet.py) with a mmdet detector. Or you can just use the [demo](https://openxlab.org.cn/apps/detail/mmpose/RTMPose) to inference your images. More examples can be seen in mmpose's README.

we must install mmpose?

**Comment by yzd-v** [comment]
No, just opencv is fine. Please refer branch opencv_onnx.

**Comment by github-luffy** [comment]
> No, just opencv is fine. Please refer branch opencv_onnx.

Thanks. I use top_with_mmdet.py with dw-ll_ucoco_384.pth. The Speed is slow. It costs about 100ms every pic. And it is right?

**Comment by github-luffy** [comment]
> > The config for dw-ll_ucoco_384.pth is [this](https://github.com/IDEA-Research/DWPose/blob/main/mmpose/configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py). You can find it in README. You can refer the Test a model in README to test it. If you want to inference for your own images, you can refer [top_with_mmdet.py](https://github.com/IDEA-Research/DWPose/blob/main/mmpose/demo/topdown_demo_with_mmdet.py) with a mmdet detector. Or you can just use the [demo](https://openxlab.org.cn/apps/detail/mmpose/RTMPose) to inference your images. More examples can be seen in mmpose's README.
> 
> we must install mmpose?

which of models is the fastest?   tiny?

**Comment by yzd-v** [comment]
Refer this [folder](https://github.com/IDEA-Research/DWPose/tree/onnx/ControlNet-v1-1-nightly/annotator/dwpose) for inference. It's very fast.

**Comment by github-luffy** [comment]
> Refer this [folder](https://github.com/IDEA-Research/DWPose/tree/onnx/ControlNet-v1-1-nightly/annotator/dwpose) for inference. It's very fast.

Thanks for your reply. The accuracy is also the best?
