### ISSUE TITLE
A1111 Extension "Install from URL" fails

### ISSUE THREAD

**Issue by calirails** [IDEA-Research/DWPose#11]
I've tried the "Install from URL" using the Github URL of https://github.com/IDEA-Research/DWPose.git but ran into an **Filename too long error** as summarized below.
```
Updating files: 22% (591/2682) Updating files: 23% (617/2682) Updating files: 24% (644/2682) Updating files: 25% (671/2682) Updating files: 26% (698/2682) Updating files: 27% (725/2682) Updating files: 28% (751/2682) error: unable to create file ControlNet-v1-1-nightly/annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierQuantizedEfficientNet.java: Filename too long error:
```

I've retried but was informed that the <a1111>/../../tmp/DWpose folder already exists. After deleting it and retrying, I get the same Filename too long error. I've even tried specifying the **main** and **onxx** branch but get the same original error. 

In every other way, my a1111 installation works well and runs without error. My OS is Windows11 and I run with an Nvidia GPU that renders efficiently. I would appreciate any guidance on what else can I try to get DWPose working. Thanks in advance.

**Comment by yzd-v** [comment]
You do not need to install DWPose. Just update your sd-webui-controlnet >= v1.1237, then choose dw_openpose_full as preprocessor. The latest sd-webui-controlnet has included DWPose.
