### ISSUE TITLE
How to use the dwpose preprocessor in comfyui

### ISSUE THREAD

**Issue by coderzhoucf** [IDEA-Research/DWPose#12]
How to use the dwpose preprocessor in comfyui

**Comment by yzd-v** [comment]
You can refer the [dwpose folder](https://github.com/IDEA-Research/DWPose/tree/opencv_onnx/ControlNet-v1-1-nightly/annotator/dwpose) to apply dwpose to comfyui. You can infer dwpose with opencv to get the pose output.

**Comment by coderzhoucf** [comment]
thanks
