### ISSUE TITLE
getting the "wrong yaml" file error. tried to get a git for it , but then it's still not generating properly due to a probable misconfuguration. 

shall i uninstall dwpose and delete control net to start over? 

any tips would be appreciated. thanks

### ISSUE THREAD

**Issue by fckbauer** [IDEA-Research/DWPose#13]

**Comment by yzd-v** [comment]
You do not need to install DWPose. Just update your sd-webui-controlnet >= v1.1237, then choose dw_openpose_full as preprocessor. Or just git clone this repo and the folder controlnet-v1-1 is available.

**Comment by fckbauer** [comment]
> You do not need to install DWPose. Just update your sd-webui-controlnet >= v1.1237, then choose dw_openpose_full as preprocessor. Or just git clone this repo and the folder controlnet-v1-1 is available.

watched a wrong tutorial on youtube then. also i was able to fix this by downloading the original .pth file for openpose 😅 thanks for the reply though 😁
