### ISSUE TITLE
if you test with this picture, still have terriable performance.

### ISSUE THREAD

**Issue by af-74413592** [IDEA-Research/DWPose#18]
![药水哥](https://github.com/IDEA-Research/DWPose/assets/74224119/7f7866e0-dd2b-44a5-a095-2d7e355562a1)

**Comment by af-74413592** [comment]
it can't recognize the front and back of the hand

**Comment by yzd-v** [comment]
I do not get what do you mean actually. Here is my result with dwpose.
![image](https://github.com/IDEA-Research/DWPose/assets/54797851/5ce3b7e9-b887-44f1-93a1-27aca9c7421c)

**Comment by af-74413592** [comment]
![00185-790185970-](https://github.com/IDEA-Research/DWPose/assets/74224119/b527bbb7-fe26-4ecc-b712-aa835f39911e)


> I do not get what do you mean actually. Here is my result with dwpose. ![image](https://user-images.githubusercontent.com/54797851/261889252-5ce3b7e9-b887-44f1-93a1-27aca9c7421c.png)

I mean if you test in sd-webui with dwpose controlnet, it still cant recognize front and back of the hand

**Comment by af-74413592** [comment]
never mind, i will close this issue.
