### ISSUE TITLE
conflict between paper and code

### ISSUE THREAD

**Issue by jaehoon00** [IDEA-Research/DWPose#23]
First of all, thank you for your great work.

I have a question about the way to calculate Lfea at the first-stage distillation.
In the paper:
![image](https://github.com/IDEA-Research/DWPose/assets/88696080/2e37979d-20ce-4007-9968-89008a518f53)
and multiply by alpha=0.00005
In the code:
https://github.com/IDEA-Research/DWPose/blob/c6af7ac1d3a3cc67cef6555b6da66f4e10097f85/mmpose/mmpose/models/losses/fea.py#L51-L56
In the code, mse sum isn't divided by C * H * W.

Can you please tell me which one is right?

**Comment by yzd-v** [comment]
Please follow the code. CHW are all stable value, which can be combined into the hyper-paremeter. The formula in the paper  follow the previous feature-based distillation style.

**Comment by jaehoon00** [comment]
Got it. Thank you.
May I ask how did you find value of alpha: 0.00005 (or 0.00007)?
Was there any knowledge or background to narrow down into this range: k * 1e-5?
Or, did you simply tried every case? like alpha = 1e-6, 1e-5, ... , 1e-2, 1e-1?
Thank you in advance!

**Comment by yzd-v** [comment]
Just keep the distillation loss and original loss in an order of magnitude. The results would not vary too much.

**Comment by jaehoon00** [comment]
Do you mean that you made the distillation loss and the original loss similar (within an order of magnitude) by using alpha?

**Comment by yzd-v** [comment]
yep
