### ISSUE TITLE
the performance of DWPose in body 2d keypoint

### ISSUE THREAD

**Issue by Phil-Lin** [IDEA-Research/DWPose#26]
hello，can you share your experimental result of DWPose in body 2d keypoint?

**Comment by yzd-v** [comment]
We try to train DWPose in Body17 on COCO. Both s1 and s2 distillation can bring improvements. But the improvement is not significant. Maybe larger datasets can further enhance distillation.

**Comment by Phil-Lin** [comment]
Thank you, I will try it on COCO + AIC;
