### ISSUE TITLE
DWPose pre-processor won’t show up

### ISSUE THREAD

**Issue by NoobArtist85** [IDEA-Research/DWPose#29]
Hi guys, I went through one of the YouTube video instructions on how t install DWPose. After the installation, DWPose comes under installed Extensions but not in the Pre- processor dropdown menu in ControlNet. What have I done wrong? 
Cheers,

**Comment by fckbauer** [comment]
if you were able to update your ControlNet to the latest version it should already be there.  Try to close the terminaln and relaunch SD again :)

**Comment by NoobArtist85** [comment]
> if you were able to update your ControlNet to the latest version it should already be there. Try to close the terminaln and relaunch SD again :)

My control net is not the latest. I tried to update it via the "check for updates" option. It shows me an update but won't run it I guess. Tried several times. The next option is to completely download the new version. I'll give it a go tonight. Thanks

**Comment by fckbauer** [comment]
make a back up of your old one and rename the folder.  then use install via URL from the repo of the new controlnet, then go to your old controlnet and copy all the files of your models folder and then paste them on the new controlNet's models folder then when it asks you if you "want to overwrite" any existing file click no or skip.  Restart Stable Diffusion by closing/terminating the terminal and relaunching SD. Then proceed to controlNet within SD and DWPose should be there on the pre-processor selection  💯 Hope this helps!
