### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './models/v1-5-pruned.ckpt'

### ISSUE THREAD

**Issue by imfurkaann** [IDEA-Research/DWPose#3]
where can i get it?

**Comment by huchenlei** [comment]
Please read the README.md under ControlNet:
https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main

**Comment by yzd-v** [comment]
> where can i get it?

You can find this in ControlNet's README.

**Comment by Ayaa17** [comment]
The link is no longer valid.
Updated link: [stable-diffusion-v1-5](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5/tree/main)
