### ISSUE TITLE
Installation failed due to Filename too long

### ISSUE THREAD

**Issue by YarivTawili** [IDEA-Research/DWPose#31]
Hi, during installation via webui11111 I'm getting this error: unable to create file ControlNet-v1-1-nightly/annotator/zoe/zoedepth/models/base_models/midas_repo/mobile/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/ClassifierFloatEfficientNet.java: Filename too long

Support of long file names is enabled on my windows.
I've read somewhere that I can run "git config --system core.longpaths true" but I'm not sure where because I tried to install DWPose via webui and I have no idea how to install it via commandline.

**Comment by yzd-v** [comment]
Just update your sd-webui-controlnet. The lataest web-controlnet has included this. You do not need to install DWPose again.

**Comment by NeoAnthropocene** [comment]
> Just update your sd-webui-controlnet. The latest web-controlnet has included this. You do not need to install DWPose again.

THanks fo the tip, I also missed that new "sd-webui-controlnet" extension update too. That helped me to work.

**Comment by MrK301** [comment]
i have the same issue with the current version of controlnet v1.1.313
