### ISSUE TITLE
DWPose Installation Error

### ISSUE THREAD

**Issue by pocoyobyte** [IDEA-Research/DWPose#32]
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- https://github.com/IDEA-Research/DWPose.git C:\Users\danie\OneDrive\Documents\A11\stable-diffusion-webui\tmp\DWPose stderr: 'fatal: destination path 'C:\Users\danie\OneDrive\Documents\A11\stable-diffusion-webui\tmp\DWPose' already exists and is not an empty directory. '
![image](https://github.com/IDEA-Research/DWPose/assets/73386092/97a03e1a-d8d6-4f3a-b82f-41222b807444)

**Comment by pocoyobyte** [comment]
Also when you delete the DWPose folder, comes up with another error and makes the folder again 

it's a "Filename too long error: unable to create file" error and it seems like i don't have DWPose file in SD A111 since it doesnt work correctly

**Comment by aziRna** [comment]
i also have the same problem, tried to do some fix attempts but didnt worked.

**Comment by merlinwarage** [comment]
git config --global core.longpaths true

**Comment by merlinwarage** [comment]
> GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- https://github.com/IDEA-Research/DWPose.git C:\Users\danie\OneDrive\Documents\A11\stable-diffusion-webui\tmp\DWPose stderr: 'fatal: destination path 'C:\Users\danie\OneDrive\Documents\A11\stable-diffusion-webui\tmp\DWPose' already exists and is not an empty directory. ' ![image](https://user-images.githubusercontent.com/73386092/264953377-97a03e1a-d8d6-4f3a-b82f-41222b807444.png)

git config --global core.longpaths true

**Comment by merlinwarage** [comment]
> Also when you delete the DWPose folder, comes up with another error and makes the folder again
> 
> it's a "Filename too long error: unable to create file" error and it seems like i don't have DWPose file in SD A111 since it doesnt work correctly

git config --global core.longpaths true

**Comment by pocoyobyte** [comment]
> > Also when you delete the DWPose folder, comes up with another error and makes the folder again
> > it's a "Filename too long error: unable to create file" error and it seems like i don't have DWPose file in SD A111 since it doesnt work correctly
> 
> git config --global core.longpaths true

I'm not that technical so I wouldn't even know where to put this + I use a one click installer for A1111

**Comment by yzd-v** [comment]
Now DWPose is just supported with sd-webui-ControlNet. You need to install sd-webui-controlnet first and then use DWPose in stable-diffusion-webui.
