### ISSUE TITLE
detect_resolution

### ISSUE THREAD

**Issue by simplaj** [IDEA-Research/DWPose#33]
i only use the dwpose , could u please tell me the detect_resolution resized in the reference.

**Comment by yzd-v** [comment]
384x288 (HxW)

**Comment by simplaj** [comment]
I apologize for bothering you again, but I would like to confirm if the "detect_resolution" in this line https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/gradio_dw_open_pose.py#L48 is set to 384x288. According to the code, it should be an integer rather than a tuple.

**Comment by yzd-v** [comment]
Integer is to resize the input. For DWPose, [640x640](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/onnxdet.py#L99) is for yolox, [384x288](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/onnxpose.py#L355) is for dwpose.

**Comment by simplaj** [comment]
thank u very much~
