### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by PublicClassHorny** [IDEA-Research/DWPose#38]
My controlnet starts bugging after i installed DW pose.
I choose preprocessor in A1111 and it starts loading endlessly. The loading line fills up over and over again. Please help.

![image](https://github.com/IDEA-Research/DWPose/assets/114310288/31793e47-0526-4d17-b7d5-0052e50ca7b2)

**Comment by fckbauer** [comment]
disable it. then just update your controlnet to the latest version. restart and you're all set.

**Comment by PublicClassHorny** [comment]
> disable it. then just update your controlnet to the latest version. restart and you're all set.

Thank you, it worked!
