### ISSUE TITLE
About openpose_hand

### ISSUE THREAD

**Issue by mrhanCH** [IDEA-Research/DWPose#39]
Hello, the effect of dwpose model is very good, but some of my projects do not need to recognize facial feature points, so do you have any plans to open a model similar to openpose_hand, which only recognizes posture and hands? Or is there any method to automatically remove facial feature points in the image generation stage?
Thank you very much!

**Comment by fckbauer** [comment]
isn't it removable via OpenPose Editor?

**Comment by yzd-v** [comment]
You can choose face, body, hand in this [file](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py#L60).

**Comment by mrhanCH** [comment]
> isn't it removable via OpenPose Editor?

yeah,but I want to process it quickly

**Comment by mrhanCH** [comment]
> You can choose face, body, hand in this [file](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py#L60).

Perfect, thank you!

**Comment by JS1989git** [comment]
> You can choose face, body, hand in this [file](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py#L60).

Can you please explain what I am supposed to do with this information? I know that op got it just from what you've said, but I've tried all kinds of edits and am not sure what I am supposed to be doing. I made a separate issue about it here: https://github.com/IDEA-Research/DWPose/issues/49

**Comment by JS1989git** [comment]
> > You can choose face, body, hand in this [file](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py#L60).
> 
> Perfect, thank you!

Would you be so kind as to let me know what I am supposed to do/how you got it to work with the information provided? I am so lost. Posted about it here: https://github.com/IDEA-Research/DWPose/issues/49
