### ISSUE TITLE
Error during the installation process.

### ISSUE THREAD

**Issue by Noire9000** [IDEA-Research/DWPose#40]
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- github.com/IDEA-Research/DWPose.git C:\Users\admin\Desktop\SD\stable-diffusion-webui\tmp\DWPose stderr: 'fatal: repository 'github.com/IDEA-Research/DWPose.git' does not exist '

Someone can help me please?

**Comment by yzd-v** [comment]
Please refer #11
