### ISSUE TITLE
Unable to install DWPose extension in automatic1111 version 1.6

### ISSUE THREAD

**Issue by godpunisher** [IDEA-Research/DWPose#42]
Hi there, I tried to install **DWPose** using **"install from URL"** option in Automatic1111 web UI, **version 1.6**, but the installation failed showing some errors. I tried _**git clone**_ in extension folder, still no success.
Surprisingly, **dw_openpose_full** was available in ControlNet extension as preprocessor and **I was able to use it**.

I also found that, there are no **DWPose** folder in extensions.
But, there was an empty an **DWPose** folder in the directory _"stable-diffusion-webui\tmp"_ .

Somehow, **"dw-ll_ucoco_384.onnx"** and **"yolox_l.onnx"** are present in _"stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\openpose"_ folder. Please check the attached screen shots. Thank you.

![DWPose installation failed](https://github.com/IDEA-Research/DWPose/assets/52278351/c9f325cb-ed88-4a67-a2c7-bd3d51d29c94)

![git pull of DWPose](https://github.com/IDEA-Research/DWPose/assets/52278351/f096d685-4427-4b82-a18c-0af6be793b93)

**Comment by yzd-v** [comment]
Please refer #31 .
