### ISSUE TITLE
Question about results in Table.1

### ISSUE THREAD

**Issue by Michel-liu** [IDEA-Research/DWPose#44]
Thanks for your work! I noticed that the caption of Table.1 mentioned "Flip test is used". Do all the compared methods use the flip-testing strategy? I can not find any idea from their papers like ZoomNAS [48]. Thanks.

**Comment by yzd-v** [comment]
The results of compared methods are refered from Tab. 6 of [RTMPose](https://arxiv.org/pdf/2303.07399.pdf). The related code is in [here](https://github.com/IDEA-Research/DWPose/blob/onnx/mmpose/mmpose/models/pose_estimators/topdown.py#L102). I think the compared methods also apply flip test.

**Comment by Michel-liu** [comment]
I get it. Thanks for the quick reply~
