### ISSUE TITLE
Error during installation using A1111 install from URL

### ISSUE THREAD

**Issue by MattRM2** [IDEA-Research/DWPose#46]
Hi,

I have this error when I tried to install DWPose : 
`    fatal: unable to checkout working tree
    warning: Clone succeeded, but checkout failed.
    You can inspect what was checked out with 'git status'
    and retry with 'git restore --source=HEAD :/'`

Do you have an idea why ?
Thank you,

Matt

**Comment by Phartona** [comment]
There is no need to install the plugin anymore if you have controlnet installed, it has been implemented there already. [#31](https://github.com/IDEA-Research/DWPose/issues/31)

**Comment by MattRM2** [comment]
Hi,

Oki thx ;)

Matt
