### ISSUE TITLE
Python script to run this?

### ISSUE THREAD

**Issue by landmann** [IDEA-Research/DWPose#50]
Anyone have a python script I can use to detect the whole body pose of objects? 

Not sure what I should do to just get a pose of an image 😕  Should I do pip install this file and then get the annotator? but I'd have to download the weights? or if I download the hf_hub files, there are so many and I don't know what any of them mean lol

Would be greatly appreciated!

**Comment by yzd-v** [comment]
This [topdown file](https://github.com/IDEA-Research/DWPose/blob/onnx/mmpose/demo/topdown_demo_with_mmdet.py) works with .pth model. This [pose file](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py) works with .onnx model. Both of them are fine to get an image.
