### ISSUE TITLE
Which model is used in the demo

### ISSUE THREAD

**Issue by matlab2017** [IDEA-Research/DWPose#54]
Dear Authors,

Which model is used in the demo (https://openxlab.org.cn/apps/detail/mmpose/RTMPose)

I tried several model and didn't get the same results as demos 

Thanks!

**Comment by yzd-v** [comment]
DWPose-Large. The input size and detector is different in the Demo.

**Comment by matlab2017** [comment]
Thank you for your reply. Could you give me more specific information, such as input size, detector method and so on.

**Comment by yzd-v** [comment]
The [demo](https://openxlab.org.cn/apps/detail/mmpose/RTMPose) is implemented by MMPose. In this repo, the input size for detector (Yolox) is 640x640. The size for pose is 384x288. Please refer [here](https://github.com/IDEA-Research/DWPose/tree/onnx/ControlNet-v1-1-nightly/annotator/dwpose)
