### ISSUE TITLE
topdown_demo_with_mmdet what is the net_config and det_checkpoint?

### ISSUE THREAD

**Issue by zengziru** [IDEA-Research/DWPose#58]
I want to inference my own images with DWPose,  I use topdown_demo_with_mmdet. However there is a det_config and det_checkpoint. I want to know what config and checkpoint should I set to get the result as you do. Thanks!

**Comment by yzd-v** [comment]
[Here](https://github.com/IDEA-Research/DWPose/tree/onnx/mmpose/demo/mmdetection_cfg) is det_config. You can get corresponding checkpoint in [mmdet](https://github.com/open-mmlab/mmdetection/tree/main)
