### ISSUE TITLE
Can not run train.py without dist_train.sh

### ISSUE THREAD

**Issue by PengEC17** [IDEA-Research/DWPose#61]
Hi, I get a problem when i tried to run train.py without dist_train.sh. I added the parent_dir of dist_train.sh in train.py by following codes:

script_dir = os.path.dirname(os.path.realpath(__file__))
parent_dir = os.path.abspath(os.path.join(script_dir, os.pardir))

if 'PYTHONPATH' in os.environ:
    os.environ['PYTHONPATH'] = parent_dir + ':' + os.environ['PYTHONPATH']
else:
    os.environ['PYTHONPATH'] = parent_dir

I run the command "python /home/xxx/DWPose/mmpose/tools/train.py --config configs/distiller/ubody/s2_dis/dwpose_l-ll__coco-ubody-256x192.py", it reports 'PoseEstimatorDistiller is not in the mmpose::model registry.

By the way, I can successfully run train.py with dist_train.sh 

Can you tell me what  I did wrong, pls~~~

**Comment by yzd-v** [comment]
When you bash dist_train.sh, you actually type the command in the shell. You can try to align the command you type with that in the train.sh. You can check more carefully. I do not know the error either.
