### ISSUE TITLE
Downloading DwPose, doesn't work.

### ISSUE THREAD

**Issue by WhoGivesOne11** [IDEA-Research/DWPose#65]
I've tried downloading DwPose correctly by going to "Extensions" and then going to "Install from URL" and then in the "URL for extension's git repository" I pasted in "https://github.com/IDEA-Research/DWPose.git" and pressed install. It then comes up with this: 
![Screenshot 2024-01-01 132532](https://github.com/IDEA-Research/DWPose/assets/155331124/d4dd7a3d-fbcf-42c8-9435-da7f8e82ccbf)

Does anybody know how to fix it?

**Comment by yzd-v** [comment]
You do not need to download dwpose.git. Just update your controlnet. The you can use dwpose.
