### ISSUE TITLE
tab.2. and tab.3. Experiments value may wrong..?

### ISSUE THREAD

**Issue by chojinie** [IDEA-Research/DWPose#69]
Hi. Thank you to open nice work.
I have a few questions.

When i was reading a paper, i found that it might be wrong expression on your description in paper on page 6 paragraph 5.2. Performance on UBody is not that correct on Table2 and 3's result.

in paragraph 5.2. Performance on UBody, you said,
"Different from COCO, the gains that our TPD brings on UBody mainly focus on the face and hand. As for COCO, the performance on the body, foot, and hand all get significant improvements, but the gains on the face are limited, as shown in Tab. 2. "

but On Tab.2 every value is improved compared with baseline. so i can agree with UBody's effect on my mind but not that agree with this description "Different from COCO, the gains that our TPD brings on UBody mainly focus on the face and hand." and also "As for COCO, the performance on the body, foot, and hand all get significant improvements, but the gains on the face are limited, as shown in Tab. 2" this description too..  i mentioned above, every result had improve.. i think.

Maybe i didn't understand your paper enough. But i think that is the wrong expression..

And, i want to know in Tab.3. why face evaluation result 73.8 is the best on RTM-l(384x288)

Please reply if you don't mind.

Sincerely,

**Comment by yzd-v** [comment]
On UBody, TBD brings 0.4, 0.3, 1.0, 1.1 AP gains for body, foot, face, hand, respectively. On COCO, TBD brings 0.7, 0.7, 0.2, 1.5 for body, foot, face, hand, respectively. So "the gains that our TPD brings on UBody mainly focus on the face and hand" and "As for COCO, the performance on the body, foot, and hand all get significant improvements, but the gains on the face are limited."

**Comment by chojinie** [comment]
@yzd-v Thanks for rapid response!
Totally understand!   I learned that I had to mix up the table 1 and 2.

**Comment by yzd-v** [comment]
Adding extra dataset (UBody) can improve the performance on COCO and UBody. And such operation is not included in TPD, which is a distillation method.

**Comment by chojinie** [comment]
Thanks!
