### ISSUE TITLE
[Request] Load and run onnx model with CV2

### ISSUE THREAD

**Issue by huchenlei** [IDEA-Research/DWPose#7]
See https://github.com/Mikubill/sd-webui-controlnet/pull/1892

Because onnxruntime still requires users to install MS Virtual C++, Lvmin suggests that we loads and run onnx model with cv2:
https://docs.opencv.org/4.8.0/d6/d0f/group__dnn.html#ga7faea56041d10c71dbbd6746ca854197

**Comment by yzd-v** [comment]
We support to run onnx model with opencv in branch [opencv_onnx](https://github.com/IDEA-Research/DWPose/tree/opencv_onnx). But we need to manually build OpenCV through cmake to work with GPU. However, according to our test, the speed is also fine with CPU.

**Comment by huchenlei** [comment]
Thanks! PR landed in ControlNet repo.
