### ISSUE TITLE
using cpu

### ISSUE THREAD

**Issue by azamet90** [IDEA-Research/DWPose#72]
is there a way to make it use gpu instead of cpu?

**Comment by yzd-v** [comment]
[Here](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/wholebody.py#L10)

**Comment by azamet90** [comment]
> [Here](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/wholebody.py#L10)

thanks for reply! but im amd user and have rocm installed. that one says cuda there?

**Comment by azamet90** [comment]
![resim](https://github.com/IDEA-Research/DWPose/assets/44042178/44ddb3b8-b117-4afb-b8d9-763e66cb86a0)
