### ISSUE TITLE
Can I track only person in multi-person video with DWPose?

### ISSUE THREAD

**Issue by Koruvika** [IDEA-Research/DWPose#77]
Video below get 2 person pose, but i don't want it. How can i track only person pose in that video?
![Uploading leg extension_1.gif…]()

**Comment by yzd-v** [comment]
You can choose the [det result](https://github.com/IDEA-Research/DWPose/blob/onnx/ControlNet-v1-1-nightly/annotator/dwpose/wholebody.py#L20) with highest score for pose detection.
