### ISSUE TITLE
How many epoch of s1_dis in whole-body and UBody??

### ISSUE THREAD

**Issue by omglet1** [IDEA-Research/DWPose#79]
I don't know how many epoch are used in s1_dis on whole-body and UBody.

![image](https://github.com/IDEA-Research/DWPose/assets/92415012/ab0e58a1-17bb-4620-8ce7-ce614311be64)

the max epoch is 270, but using cosine lr from 150 to 300 epoch.
you say the epoch of two-stage distillation is 20% of one-stage epoch in paper，the epoch of two-stage distillation is 60。

**Comment by yzd-v** [comment]
Typo. Should be from 135 to 270 epochs. S2_dis just needs to train the head, which is faster than traing the whole model. The whole training time  for s2_dis is about 20%.

**Comment by omglet1** [comment]
Thanks.  :)
