### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Charlotte-Macbeth** [IDEA-Research/DWPose#8]
When I try to use it, it gave me this error:

cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:274: error: (-5:Bad argument) Can't read ONNX file: D:\桌面\Have a good day\Stable-difussion\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\annotator\downloads\openpose\yolox_l.onnx in function 'cv::dnn::dnn4_v20230620::ONNXImporter::ONNXImporter'

I don't know how to fix it.

**Comment by yzd-v** [comment]
Make sure the yolox_l.onnx is not broken. If the error still exists, you can try to reinstall opencv.
