### ISSUE TITLE
How to use the weights in .pth format?

### ISSUE THREAD

**Issue by seekFire** [IDEA-Research/DWPose#81]
![2024-04-01 09-57-30 的屏幕截图](https://github.com/IDEA-Research/DWPose/assets/26456083/b65fdce9-1e90-4681-89ea-01e0e4bde1a9)
The ckpt links in the table below is in .pth format, so which branch of this repo can use it?
BTW, Is DWPose for ControlNet used in **onnx** branch?
![Uploading 2024-04-01 10-35-40 的屏幕截图.png…]()

**Comment by yzd-v** [comment]
Main branch is for pth. All the branches can be used for controlnet.

**Comment by seekFire** [comment]
@yzd-v Thank you very much!
