### ISSUE TITLE
Demo ignores the hand

### ISSUE THREAD

**Issue by liqi-shu** [IDEA-Research/DWPose#9]
Dear DWPose team, 

The demo seems ignore the hands estimation : https://openxlab.org.cn/apps/detail/mmpose/RTMPose

Thanks for checking!

**Comment by yzd-v** [comment]
You should choose wholebody here.
![image](https://github.com/IDEA-Research/DWPose/assets/54797851/4ff04fee-12e7-4980-8912-92a98214c859)
