### ISSUE TITLE
i got 'ValueError'

### ISSUE THREAD

**Issue by repenbaa** [IDEA-Research/DWPose#99]
i try to run dwpose_infer_example.py but i got an error

dwpose_infer_example.py->
from annotator.dwpose import DWposeDetector

if name == "main":
pose = DWposeDetector()
import cv2
test_image = r'C:~\example_data\motions\motion-02\normal\0002_all.png'
oriImg = cv2.imread(test_image) # B,G,R order
import matplotlib.pyplot as plt
out = pose(oriImg)
plt.imsave(test_image, out)
<-

ValueError: not enough values to unpack (expected 2, got 1)->

C:\DWPose-onnx\ControlNet-v1-1-nightly\dwpose_infer_example.py", line 9, in
out = pose(oriImg)
C:\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose_init_.py", line 41, in call
candidate, subset = self.pose_estimation(oriImg)
C:\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose\wholebody.py", line 21, in call
keypoints, scores = inference_pose(self.session_pose, det_result, oriImg)
C:\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose\onnxpose.py", line 358, in inference_pose
keypoints, scores = postprocess(outputs, model_input_size, center, scale)
C:\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose\onnxpose.py", line 104, in postprocess
simcc_x, simcc_y = outputs[i]
ValueError: not enough values to unpack (expected 2, got 1)
<-

but i guess the problem is the model output is now different->

[array([[[ 2.1711223e+00, 2.8624635e+00, 1.7922809e+00, ...,
2.5836229e-03, 3.3175349e-03, 7.4857473e-04],
[ 1.5999658e+00, 3.3495755e+00, 1.8548770e+00, ...,
3.4599304e-03, 2.9240847e-03, 5.3149462e-04],
[ 3.0901601e+00, 6.6307598e-01, 2.1546037e+00, ...,
7.9732537e-03, 4.3115020e-03, 1.1935234e-03],
...,
[ 5.0059336e-01, -5.5438775e-01, 2.4603164e+00, ...,
1.2440503e-02, 5.2298903e-03, 8.7556839e-03],
[ 1.1096862e-01, -6.4041942e-01, 2.4406323e+00, ...,
1.0878384e-02, 4.2094588e-03, 7.6485276e-03],
[-3.1452519e-01, -1.7322320e-01, 1.5787270e+00, ...,
7.5721145e-03, 3.9893389e-03, 5.6889057e-03]]], dtype=float32)]
<-

**Comment by repenbaa** [comment]
> **i try to run dwpose_infer_example.py but i got an error**
> 
> ---dwpose_infer_example.py--- from annotator.dwpose import DWposeDetector
> 
> ## if **name** == "**main**":
> pose = DWposeDetector()
> import cv2
> test_image = r'C:~\example_data\motions\motion-02\normal\0002_all.png'
> oriImg = cv2.imread(test_image) # B,G,R order
> import matplotlib.pyplot as plt
> out = pose(oriImg)
> plt.imsave(test_image, out)
> ## ---ValueError: not enough values to unpack (expected 2, got 1)---
> C:~\DWPose-onnx\ControlNet-v1-1-nightly\dwpose_infer_example.py", line 9, in
> out = pose(oriImg)
> C:~\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose__init__.py", line 41, in **call**
> candidate, subset = self.pose_estimation(oriImg)
> C:~\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose\wholebody.py", line 21, in **call**
> keypoints, scores = inference_pose(self.session_pose, det_result, oriImg)
> C:~\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose\onnxpose.py", line 358, in inference_pose
> keypoints, scores = postprocess(outputs, model_input_size, center, scale)
> C:~\DWPose-onnx\ControlNet-v1-1-nightly\annotator\dwpose\onnxpose.py", line 104, in postprocess
> simcc_x, simcc_y = outputs[i]
> ValueError: not enough values to unpack (expected 2, got 1)
> **but i guess the problem is model output change like:**
> 
> [array([[[ 2.1711223e+00, 2.8624635e+00, 1.7922809e+00, ..., 2.5836229e-03, 3.3175349e-03, 7.4857473e-04], [ 1.5999658e+00, 3.3495755e+00, 1.8548770e+00, ..., 3.4599304e-03, 2.9240847e-03, 5.3149462e-04], [ 3.0901601e+00, 6.6307598e-01, 2.1546037e+00, ..., 7.9732537e-03, 4.3115020e-03, 1.1935234e-03], ..., [ 5.0059336e-01, -5.5438775e-01, 2.4603164e+00, ..., 1.2440503e-02, 5.2298903e-03, 8.7556839e-03], [ 1.1096862e-01, -6.4041942e-01, 2.4406323e+00, ..., 1.0878384e-02, 4.2094588e-03, 7.6485276e-03], [-3.1452519e-01, -1.7322320e-01, 1.5787270e+00, ..., 7.5721145e-03, 3.9893389e-03, 5.6889057e-03]]], dtype=float32)]
> 
> **so output got worng** : simcc_x, simcc_y = outputs[i]

**Comment by DariaShel** [comment]
Hi! I'm facing the same problem. How did you solve it?
